site_name: "ZoteroCLI - Tool for manipulating Zotero references"
repo_url: https://github.com/dhondta/zotero-cli
site_author: dhondta
docs_dir: doc
pages:
  - Introduction: index.md
  - Using Zotero-CLI: usage.md
  - FAQ: faq.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
